
server:
  port: 0  # 두개 띄웠을 때 구분이 안 간다. 
  #port: 9001
  #구분 위해 아래 eureka.instance.instance-id 셋탱해주고..  기동 시 넣어 놓았던 -Dserver.port=9002 설정 제거
  
spring:
  application:
    name: user-service    # [5-1] ->  #name: user-service0
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    #generate-unique-name: false
    driverClassName: org.h2.Driver
    username: sa
    password: 
    
eureka:
  instance:
    #instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

greeting: # 임의로 작성한 값
  message: Welcome to the Simple E-commerce.

logging:
  level:
    '[com.example.userservice]': DEBUG

#token:
#  expiration_time: 86400000  # 60초 * 60분 * 24 시간 * 1000 (ms)
#  # secret: user_token  # 임의의 값. 토큰 만들 때 사용
#  # The specified key byte array is 128 bits which is not secure enough for any JWT HMAC-SHA algorithm. 
#  # 더 길게 ..
#  secret: mynameisjiniparkiliveinyonginsin
# => [section 7] 주석으로 막는다

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans
        
