server:
  port: 8888
  
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          #uri: file://D:\dev\Git\git-local-repo
          # section 7 원격 접속
          uri: https://github.com/s-jinipark/spring-cloud-config.git
          